package deploy

import (
	"bytes"
	"fmt"
	"os"
	"text/template"
)

type initData struct {
	Name     string
	Port     int
	JobsOnly bool
}

// Init writes a unit.toml scaffold to the current directory.
// It refuses to overwrite an existing file.
func Init(name string, port int) error {
	if _, err := os.Stat("unit.toml"); err == nil {
		return fmt.Errorf("unit.toml already exists — delete it first if you want to regenerate")
	}

	data := initData{
		Name:     name,
		Port:     port,
		JobsOnly: port == 0,
	}

	t, err := template.New("init").Parse(initTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse init template: %w", err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return fmt.Errorf("failed to render init template: %w", err)
	}

	if err := os.WriteFile("unit.toml", buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("failed to write unit.toml: %w", err)
	}

	return nil
}

const initTemplate = `# unit.toml
# Generated by 'unit init'. Edit what you need, delete what you don't.
# Deploy with: unit deploy -e <env>
#
# Environment overrides live in unit.<env>.toml (e.g. unit.prod.toml).
# Put server host, domain, and secrets script there — not here.
# This file describes what your app is. The env file describes where it runs.

# Logical name of the service.
# Used for systemd unit names, release directories, and log identifiers.
name = "{{.Name}}"

# Path to the statically compiled binary, relative to the repo root.
# Build it with: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/{{.Name}} .
executable = "bin/{{.Name}}"
{{if not .JobsOnly}}
# Port the service listens on via systemd socket activation.
# systemd holds the socket open across binary swaps — connections are never dropped.
# Remove this line (or set port = 0) for jobs-only deployments.
port = {{.Port}}
{{end}}
# Override the default deployment root on the server.
# deploy_path = "/opt/unit"


# ----------------------------------------------------------------------------
# Server — put this in unit.<env>.toml, not here
# ----------------------------------------------------------------------------
# [server]
# host = "myserver"       # SSH hostname or alias
# user = "deploy"         # SSH user — needs sudo for systemd and /etc/systemd/system
# ssh_port = 22
# timeout = 30
# strict_host_key_checking = true


# ----------------------------------------------------------------------------
# Proxy
# ----------------------------------------------------------------------------
# Public domain. If set, unit writes a Caddy config snippet and reloads Caddy.
# Caddy handles TLS automatically. Put this in unit.<env>.toml.
# domain = "{{.Name}}.example.com"


# ----------------------------------------------------------------------------
# Secrets
# ----------------------------------------------------------------------------
# Path to a local shell script that exports secrets as environment variables.
# unit runs this at deploy time and uploads the values to
# /etc/credentials/{{.Name}}/ on the server via systemd LoadCredential=.
# At runtime, secrets are files under $CREDENTIALS_DIRECTORY/<SECRET_NAME>.
# secrets = "./get-secrets.sh"


# ----------------------------------------------------------------------------
# Sandbox
# ----------------------------------------------------------------------------
# The default sandbox is maximum restriction — read-only filesystem,
# no outbound network, ephemeral user, no capabilities.
# Everything below is an explicit opt-in.
[sandbox]

# Allow outbound TCP connections (e.g. to a database or external API).
# Off by default. Your app cannot make outgoing connections unless this is true.
allow_outbound_network = false

# Persistent storage at /var/lib/{{.Name}}, owned by the service user.
# Survives restarts and redeployments. Accessible at runtime via $STATE_DIRECTORY.
# state_directory = false

# Log directory at /var/log/{{.Name}}, owned by the service user.
# Accessible at runtime via $LOGS_DIRECTORY.
# logs_directory = false

# Paths the service is allowed to write to in addition to the above.
# Everything else on the filesystem is read-only.
# writable_paths = ["/var/data/{{.Name}}"]

# Allow mmap(PROT_WRITE|PROT_EXEC). Required for JIT-based runtimes such as
# DuckDB (LLVM), LuaJIT, and V8. Off by default — only enable if your binary
# embeds or execs a JIT compiler.
# allow_write_execute = false


# ----------------------------------------------------------------------------
# Dependencies
# ----------------------------------------------------------------------------
# Control when systemd starts this service relative to other units.
# after    = ordering only — start after these units are running
# requires = hard dependency — stop this service if a required unit fails
# wants    = soft dependency — try to start these units, but don't fail if unavailable
#
# Common values:
#   "network-online.target"  — wait for a network interface to be fully up
#                              (use this instead of network.target for anything
#                              that opens outbound connections)
#   "postgresql.service"     — wait for a local database
#   "redis.service"          — wait for a local cache
#
# [depends_on]
# after    = ["network-online.target", "postgresql.service"]
# requires = ["postgresql.service"]
# wants    = ["redis.service"]


# ----------------------------------------------------------------------------
# Resources
# ----------------------------------------------------------------------------
# Uncomment to set explicit resource limits via cgroups.
# Without these, the service runs unconstrained.
#
# [resources]
# memory_max = "512M"    # Hard limit — process is OOM-killed if exceeded
# memory_high = "400M"   # Soft limit — throttled before hitting the hard ceiling
# cpu_quota = "100%"     # Fraction of one CPU core. 200% = two full cores.
# tasks_max = 512        # Max threads + processes. Prevents fork bombs.


# ----------------------------------------------------------------------------
# Static environment variables
# ----------------------------------------------------------------------------
# Non-secret config injected into the service as environment variables.
# For secrets (API keys, passwords), use the secrets script above instead.
#
# [env]
# LOG_LEVEL = "info"
# APP_ENV = "production"


# ----------------------------------------------------------------------------
# Scheduled jobs
# ----------------------------------------------------------------------------
# Each [[jobs]] entry generates a <name>-<command>.service + .timer unit pair.
# The same binary is invoked as: ./bin/{{.Name}} <command>
# Jobs inherit the sandbox and credentials of the main service.
# You can have multiple [[jobs]] blocks.
{{- if .JobsOnly}}
#
# This deployment has no long-running service (no port configured).
# Add at least one [[jobs]] block below.

[[jobs]]
command = "run"
on_calendar = "daily"
persistent = true    # catch up on missed runs if the server was down
{{- else}}
#
# [[jobs]]
# command = "cleanup"
# on_calendar = "daily"
# persistent = true    # catch up on missed runs if the server was down
{{- end}}
`
